### PR TITLE
Update to version 3.2.0

### PR DESCRIPTION
**Pull request by synapticarbors**

### CODE REVIEW

**Comment by synapticarbors** [comment]
This is failing because `tzlocal` needs to be updated as well. Working on that PR now...

**Comment by synapticarbors** [comment]
Waiting on conda-forge/tzlocal-feedstock/pull/1

**Comment by jakirkham** [comment]
Nice changes @synapticarbors ! 👍

Care to take a look, @ddunwoody?

**Comment by ddunwoody** [comment]
:+1: Looks good.  Shall I merge @synapticarbors, @jakirkham?

**Comment by synapticarbors** [comment]
@ddunwoody I think it should be good to go. Thanks for reviewing the PR

**Pull request merged**
